name: π“– Documentation Suggestion
description: Docsμ— κ°μ„ ν•κ³  μ‹¶μ€ λ¬Έμ λ‚, κ¶κΈν•μ‹  μ‚¬ν•­μ΄ μλ‚μ”?
title: '[π“–] μ μ•ν•κ³  μ‹¶μ€ λ‚΄μ©μ΄λ‚ λ¬Έμ μ— λ€ν•΄ κ°„λµν• μ λ©μ„ μ‘μ„±ν•΄μ£Όμ„Έμ”'
labels: ['docs']
body:
  - type: markdown
    attributes:
      value: |
        Docs κ°μ„ μ— κ΄€μ‹¬μ„ κ°–κ³  λ°©λ¬Έν•΄μ£Όμ…”μ„ κ°μ‚¬ν•©λ‹λ‹¤! 
        μ €ν¬ docsμ—λ” λ¨λ“  νμ΄μ§€μ— `Edit this page`λΌλ” λ²„νΌμ΄ μμµλ‹λ‹¤. μ§μ ‘ μμ •ν•μ‹¤ μ μλ” λ‚΄μ© κ°™μ•„λ³΄μΈλ‹¤λ©΄, PRμ„ λ€μ‹  ν™μ©ν•΄μ£Όμ„Έμ”!
        ![Screenshot](https://github.com/minsoo-web/ETC/assets/57122180/e713855b-e86b-4006-9b2c-532422deacb8)

  - type: textarea
    id: description
    attributes:
      description: μ μ•ν•κ³  μ‹¶μ€ λ‚΄μ©μ„ μμ„Έν•κ³  λ…ν™•ν•κ² μ‘μ„±ν•΄μ£Όμ„Έμ”!
      label: μ μ•μ‚¬ν•­
    validations:
      required: true
